#!/usr/bin/env python3

import sys
import sw

__author__ = "Gabriel T. Sharp"

"""
sw
a shell-based web search initiator
Shell-Compatible Executor Shim
"""

sw.run.ProgramName = sys.argv[0]
sw.run(sys.argv[1:])
